apiVersion: v1

kind: ReplicationController

metadata:
  name: my-app
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
        location: poland
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
