apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    name: simple-pod
spec:
  containers:
    - name: simple-web-app
      image: andriizilnyk/simple-express-app
      ports:
        - containerPort: 3200
      envFrom:
        - configMapRef:
            name: app-config
