apiVersion: v1
kind: Pod
metadata:
  name: simple-express
  labels:
    name: simple-express-app
spec:
  containers:
    - name: simple-express
      image: simple-express-app
      ports:
        - containerPort: 3200
      envFrom:
        - secretRef:
            name: app-secret
